url: "http://sakaricajanus.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/new-homepage" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.
